samples_tsv: config/samples.tsv

params:
  chopper:
    q: 10
    minlength: 1000
  flye:
    mode: "--nano-hq"
  medaka:
    enabled: true
    model: "r1041_e82_400bps_hac_v5.0.0"
  prokka:
    enabled: true
  checkm:
    enabled: true
  id_genes:
    enabled: true
  amrfinder:
    enabled: true
    db: "db/amrfinder_db"